global:
  namespace: sdjpa-order-service-mysql

mysql:
  port: 3306
  targetPort: 3306
  nodePort: 30306
  
  database: "orderservicedb"

  adminUser: bookadmin
  adminPassword: password

  user: bookuser
  password: password

  rootPassword: password